name: "Release"

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Trigger on version tags

env:
  ACTIONS_STEP_DEBUG: true
  PROJECT_NAME: calculator

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: token_calculator-linux
            asset_name: token_calculator-linux
          - os: windows-latest
            artifact_name: token_calculator-windows
            asset_name: token_calculator-windows.exe
          - os: macos-latest
            artifact_name: token_calculator-macos
            asset_name: token_calculator-macos

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    
    - name: Prepare artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir artifacts
        copy target/release/calculator.exe artifacts/${{ matrix.asset_name }}
      shell: pwsh
  
    - name: Prepare artifacts (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir artifacts
        cp target/release/calculator artifacts/${{ matrix.asset_name }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: artifacts/${{ matrix.asset_name }}
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Only run on tags
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}